import { useParams, Link } from 'react-router-dom';
import Navbar from '../components/Navbar';

export default function AdvisoryDetail() {
  const { id } = useParams();

  return (
    <>
      <Navbar variant="app" />
      <main className="page-content">
        <div className="container" style={{ maxWidth: 700, paddingTop: 'var(--space-6)' }}>
          <Link to="/app" className="btn btn-ghost mb-4" style={{ padding: '8px 0' }}>
            ← Back to Advisories
          </Link>

          <div className="card card-advisory severity-critical" style={{ padding: 'var(--space-5)' }}>
            <span className="badge badge-critical mb-3">🔴 CRITICAL</span>
            <h2 style={{ marginBottom: 'var(--space-3)' }}>
              Cyclone DANA — Return to Shore Immediately
            </h2>
            <p className="mono mb-3" style={{ fontSize: 'var(--text-xs)', color: 'var(--tc-text-tertiary)' }}>
              ADV-2026-001 • IMD • CYCLONE WARNING • 6:00 AM
            </p>
            <p className="text-secondary mb-4" style={{ lineHeight: 1.7 }}>
              Cyclone DANA expected to cross north Odisha and West Bengal coasts between
              Puri and Sagar Island during late night of 24th October to early morning of
              25th October with wind speed of 100-110 kmph gusting to 120 kmph. Storm surge
              of about 1-2 metres expected. All fishing operations should cease immediately.
              Fishermen are advised not to venture into sea.
            </p>

            <h4 className="mb-3">Affected Zones</h4>
            <div className="flex gap-2 mb-4" style={{ flexWrap: 'wrap' }}>
              {['Puri', 'Paradip', 'Gopalpur'].map(z => (
                <span key={z} className="badge badge-critical">{z}</span>
              ))}
            </div>

            <h4 className="mb-3">Audio Advisory</h4>
            <div className="audio-player mb-4">
              <button className="audio-play-btn" aria-label="Play advisory audio" style={{ width: 56, height: 56, minWidth: 56, fontSize: '1.5rem' }}>
                ▶
              </button>
              <div style={{ flex: 1 }}>
                <div className="mono" style={{ fontSize: 'var(--text-sm)', color: 'var(--tc-ink)' }}>
                  English Audio
                </div>
                <div className="mono" style={{ fontSize: 'var(--text-xs)', color: 'var(--tc-text-tertiary)' }}>
                  DURATION: 0:42 • GENERATED BY CLOUD TTS
                </div>
                <div style={{ height: 6, background: 'var(--tc-border)', marginTop: 8 }}>
                  <div style={{ height: 6, width: '0%', background: 'var(--tc-ocean-blue)' }} />
                </div>
              </div>
            </div>

            <div className="flex gap-2 mb-4">
              {['Tamil', 'Telugu', 'Odia'].map(lang => (
                <button key={lang} className="btn btn-secondary" style={{ fontSize: 'var(--text-xs)', padding: '8px 14px' }}>
                  ▶ {lang}
                </button>
              ))}
            </div>

            <button className="btn btn-primary btn-lg w-full">
              ✓ I Received This — Mark as Safe
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
